version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: unless-stopped

  rabbit:
    image: rabbitmq:3-management
    ports:
      - "5673:5672"     # AMQP
      - "15673:15672"   # UI dashboard
    restart: unless-stopped

  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - rabbit
    restart: unless-stopped

  celery:
    build: .
    command: >
      sh -c "sleep 10 && celery -A djangoshop worker --loglevel=info"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - web
      - rabbit
    restart: unless-stopped

volumes:
  postgres_data:
