# Generated by Django 5.0.2 on 2024-03-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_otpcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otpcode",
            name="phone_number",
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
