# Generated by Django 5.0.2 on 2024-03-12 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_sub",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="category",
            name="sub_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scategory",
                to="home.category",
            ),
        ),
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ManyToManyField(related_name="products", to="home.category"),
        ),
    ]
