# Generated by Django 5.0.2 on 2024-03-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_category_is_sub_category_sub_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(),
        ),
    ]
